name: Green Pencil Schema Docs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'main'
jobs:
  Generate-Schema-Docs:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download PostgreSQL JDBC Driver
        run: wget https://jdbc.postgresql.org/download/postgresql-42.2.14.jar                
      - name: Download SchemaSpy
        run: wget https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar
