name: Green Pencil Schema Docs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'main'
jobs:
  Generate-Schema-Docs:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download PostgreSQL JDBC Driver
        run: wget https://jdbc.postgresql.org/download/postgresql-42.2.14.jar
      - name: Install Graphviz
        run: sudo apt-get install graphviz        
      - name: Download SchemaSpy
        run: wget https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar
      - name: Run SchemaSpy
        run: |
          java -jar schemaspy-6.1.0.jar -t pgsql \
            -dp postgresql-42.2.14.jar \
            -db test \
            -host ep-solitary-river-a1vsgyfp.ap-southeast-1.aws.neon.tech \
            -port 5432 \
            -u test_owner \
            -p ${{ secrets.DB_PASSWORD }} \
            -connprops sslmode\\=require \
            -o ./schemaspy-output \
            -debug
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      - name: Upload SchemaSpy Output as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: schemaspy-docs
          path: ./schemaspy-output/
          
